create base user & tasks pages
htmlacademy-yii/514921-task-force-1 pull request #11
Opened 2020-03-08 09:14 UTC by reymezis

2020-03-09 05:59 UTC, b1rdex requested changes

2020-03-09 05:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        $tasks = Tasks::find()->addOrderBy(['date_add'=> SORT_ASC])->all();
Показывать надо только задания в статусе «Новое»

2020-03-09 05:59 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        $tasks = Tasks::find()->addOrderBy(['date_add'=> SORT_ASC])->all();
Сортировка, по-моему, должна быть наоборот – сначала новые, потом старые

2020-03-09 05:59 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +        $users = Profiles::find()->all();
Почему не Users? И нужно показывать только с ролью «Исполнитель»

2020-03-12 14:19 UTC, reymezis commented
почему то не отображается информация из профиля поля 'about'

2020-03-13 04:34 UTC, merged