Module7 task3
htmlacademy-yii/514921-task-force-1 pull request #17
Opened 2020-05-06 13:39 UTC by reymezis

2020-05-08 07:09 UTC, b1rdex requested changes

2020-05-08 07:09 UTC, b1rdex commented on console/migrations/m200428_180637_add_price_column_to_replies_table.php
> +            $this->decimal(10, 0)
Цена там без знаков после запятой? Тогда можно было сделать и int. Можно не исправлять, это не критично.

2020-05-08 07:09 UTC, b1rdex commented on frontend/models/Replies.php
> +            [['status'], 'string', 'max' => 255],
В бд у тебя это просто строка и в модели просто строка. Но я так понимаю там есть список возможных значений. Нужно либо в бд сделать enum, либо здесь в модели сделать валидацию значения

2020-05-08 07:09 UTC, b1rdex commented on console/migrations/m200507_165319_set_status_default_value_to_tasks_table.php
> +        return false;
return false убрать

2020-05-08 07:09 UTC, b1rdex commented on console/migrations/m200507_165725_add_status_value_to_tasks_table.php
> +        return false;
Про это писал отдельно, нужно убрать

2020-05-08 07:09 UTC, b1rdex commented on frontend/controllers/SiteController.php
>      public function actionLogin()
Этот экшн вообще используется? Вспывающая форма авторизации отправляет данные в landing. Сюда можно попасть только если вручную зайти на /site/login

2020-05-08 07:09 UTC, b1rdex commented on frontend/controllers/SiteController.php
> +        if (Yii::$app->user->isGuest) {
Было: если уже авторизован, то отправить на главную. А сейчас через этот экшн авторизоваться не получится, т.к. всех гостей он переадресовывает на /

2020-05-08 07:09 UTC, b1rdex commented on frontend/models/ReplyForm.php
> +            ['price', 'integer', 'integerOnly' => true, 'min' => '1',
Я писал о том что оно у тебя decimal, теперь понятно что там int. Оставляй так, это не важно.

2020-05-08 07:09 UTC, b1rdex commented on src/services/TaskService.php
> +    public function completeTask($form, $taskId)
Добавь, пожалуйста, тип к $form, чтобы было понятно какая форма

2020-05-08 07:09 UTC, b1rdex commented on src/services/TaskService.php
> +        $task = Tasks::findOne($taskId);
Стоит либо в метод передавать объект Tasks, либо здесь нужно убедиться что findOne вернул результат

2020-05-08 07:09 UTC, b1rdex commented on src/services/TaskService.php
> +        }
1. стоит это немного переписать, убрав дублирующийся код
2. у вас в критериях вроде бы нет требований к использованию транзакций, но если вы их изучали (я не помню есть ли они в рамках курса), стоит $task->save и $review->save делать в рамках одной транзакции

2020-05-08 07:09 UTC, b1rdex commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
Добавь класс form-modal-close, чтобы оно закрывало модалку

2020-05-08 07:09 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
Ещё нужно task id указать в параметрах запроса

2020-05-08 08:19 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
Зачем ?

2020-05-08 08:20 UTC, reymezis commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
добавил, тогда кнопка Отмена вообще не отображается

2020-05-08 08:24 UTC, reymezis commented on src/services/TaskService.php
> +        }
Т.е это решит сделать две отдельные транзакции на условия STATUS_COMPLETED и STATUS_FAILED ?

2020-05-08 08:31 UTC, reymezis commented on src/services/TaskService.php
> +        $task = Tasks::findOne($taskId);
а как быть с findOne в других экшэнах и формах ?

2020-05-08 08:49 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
Насколько я понял, $postedReply это отклик текущего пользователя. Task id нужно указать, чтобы выбрать отклик только к заданию, которое смотрим. Иначе всегда будет выбираться первый отклик из бд, не важно к какому заданию

2020-05-08 08:50 UTC, b1rdex commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
Прикольно. Тогда сделай кастомный js по клику на эту кнопку, который вызовет  `closeModal()`

2020-05-08 08:50 UTC, b1rdex commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
frontend/web/js/main.js:17

2020-05-08 08:51 UTC, b1rdex commented on src/services/TaskService.php
> +        $task = Tasks::findOne($taskId);
Ну я заметил только здесь, но вообще это применимо ко всем остальным местам так же. Если что-то достаёшь из бд, надо убедиться что там не null. Либо передавать уже объект

2020-05-08 09:24 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
в $postedReply выбирается не первый отклик из бд, а отклик того кто его оставил, для показа только автору этого отлика, когда он залогинен

2020-05-08 09:27 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
> Иначе всегда будет выбираться первый отклик из бд, не важно к какому заданию
не могу понять при каком сценарии это может происходить

2020-05-08 09:30 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
А сами отклики уже берутся из $task->replies as $reply

2020-05-08 10:15 UTC, reymezis commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
не знаю как это сделать

2020-05-08 11:17 UTC, reymezis commented on src/services/TaskService.php
> +        }
или речь только о $task->save() и $review->save в одну транзакцию для двух случаев ?

2020-05-08 11:28 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
Пользователь может писать отклики на каждый task. Т.к. в условии запроса ты указываешь только user id, то выберется первый попавшийся отклик из бд, не важно от какого task.

2020-05-08 11:44 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        $postedReply = Replies::findOne(['user_id' => "{$currentUser->id}"]);
понял

2020-05-12 04:14 UTC, b1rdex commented on src/services/TaskService.php
> +        }
Я проверил, не вижу у вас в учебнике ничего про транзакции, пропустим этот момент.

2020-05-12 04:22 UTC, b1rdex requested changes

2020-05-12 04:22 UTC, b1rdex commented on src/services/TaskService.php
> +        }
Вот что я имел в виду, говоря о том, что нужно убрать дублирование кода:

```suggestion
        $task->status = $form->isComplete === 'yes' ? Task::STATUS_COMPLETED : Task::STATUS_FAILED;
        $task->save();

        $review->task_id = $taskId;
        $review->user_id = $task->contractor_id;
        $review->review = $form->review;
        $review->rating = $form->rating;
        $review->task_completion_status = $form->isComplete === 'yes' ? 'yes' : 'no';

        return $review->save();
```

2020-05-12 04:22 UTC, b1rdex commented on frontend/views/tasks/view.php
> +        'class' => 'button__form-modal button',
Я посмотрел view.html, в нём добавлен `id="close-modal"` к этой кнопке, ты его потерял при переносе. Он должен закрывать форму, это есть в main.js. Так что попробуй добавить сюда id

2020-05-12 07:57 UTC, merged