Module8 task3
htmlacademy-yii/514921-task-force-1 pull request #20
Opened 2020-07-08 16:39 UTC by reymezis

2020-07-24 00:26 UTC, b1rdex requested changes

2020-07-24 00:26 UTC, b1rdex commented on common/mail/newMessage-html.php
> +    <p><?= Html::a('Посмотреть сообщение', "/task/view/<?=$data->task_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on common/mail/newReply-html.php
> +    <p><?= Html::a('Посмотреть отклик', "/task/view/<?=$data->task_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on common/mail/newReview-html.php
> +    <p><?= Html::a('Посмотреть отзыв', "/user/view/<?=$data->user_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on common/mail/taskComplete-html.php
> +    <p><?= Html::a('Посмотреть задание', "/task/view/<?=$data->task_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on common/mail/taskDecline-html.php
> +    <p><?= Html::a('Посмотреть задание', "/task/view/<?=$data->task_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on common/mail/taskStart-html.php
> +    <p><?= Html::a('Посмотреть задание', "/task/view/<?=$data->task_id?>") ?></p>
Нужна абсолютная ссылка

2020-07-24 00:26 UTC, b1rdex commented on console/migrations/m200611_175408_drop_address_column_from_profiles_table.php
> +    {
Не хватает миграции вниз

2020-07-24 00:26 UTC, b1rdex commented on frontend/web/account.html
>          <div class="main-container page-header__container">
Этот файл вроде надо удалить?

2020-07-24 00:26 UTC, b1rdex commented on frontend/controllers/EventsController.php
> +        if (Yii::$app->request->isGet) {
Думаю эту проверку можно убрать

2020-07-24 00:26 UTC, b1rdex commented on frontend/models/SettingsForm.php
> +        $avatar->saveAs($avatarDir . $avatar->getName());
Будет конфликт имён, если загрузить несколько файлов с одинаковым названием. Надо что-то рандомное в имя добавить, либо полностью подменять имя (например на хэш) для хранения на диске, а оригинальное имя записывать в бд

2020-07-24 00:26 UTC, b1rdex commented on frontend/models/SettingsForm.php
> +        $userPicturesDir = __DIR__ . '/../../frontend/web/uploads/';
Наверно стоит в uploads сделать две подпапки, одну для аватаров, другую для загрузок

2020-07-24 00:26 UTC, b1rdex commented on frontend/views/layouts/main.php
> +$events = $user->getEvents()->Where(['notification_read' => null])->all();
Это нарушает критерий https://up.htmlacademy.ru/yii/1/criteries#b22, надо куда-то вынести.
Либо хотя бы спрятать это в какой-то метод внутри User, чтобы было `foreach ($user->getUnreadNotifications() as $notification)` вместо явного запроса из шаблона

2020-07-24 00:26 UTC, b1rdex commented on src/services/EventService.php
> +//        $eventNewMessage->user_id = $task->messages;
Без этого не сохранится, там же not null

2020-07-24 18:00 UTC, reymezis commented on frontend/web/account.html
>          <div class="main-container page-header__container">
бойлерплейт думаю в конце удалить

2020-07-24 18:00 UTC, reymezis commented on frontend/controllers/EventsController.php
> +        if (Yii::$app->request->isGet) {
а там же вроде именно get запрос должен прийти

2020-07-24 18:01 UTC, reymezis commented on src/services/EventService.php
> +//        $eventNewMessage->user_id = $task->messages;
логику просмотра новых сообщений как раз ещё не сделал, соотвественно и уведомления пока ещё не работают

2020-07-30 10:58 UTC, b1rdex approved these changes

2020-07-30 10:59 UTC, merged