Module9 task2
htmlacademy-yii/514921-task-force-1 pull request #22
Opened 2020-08-30 16:43 UTC by reymezis

2020-09-02 04:44 UTC, b1rdex requested changes

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/LocationController.php
> +        $cacheData = Yii::$app->cache->get($hashKey);
> предусмотрите ситуацию, когда хранилище кэша недоступно: приложение не должно; завершаться ошибкой, а юзер получает координаты напрямую из API.

Нужно обернуть получение данных из кэша и запись в кэш в try-catch, чтобы игнорировать ошибку.

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/LocationController.php
> +            Yii::$app->cache->set($hashKey, $result, 86400);
Выше у тебя есть логика, которая изменяет ответ api в зависимости от текущего пользователя. Так что кэшировать модифицированный вариант неправильно, иначе у других пользователей могут возникнуть из-за этого ошибки. Я бы в этой задаче кэшировал целиком ответ api, а потом уже менял/фильтровал всё что там нужно.

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +        ]);
Для чего тут or? Не могу понять логики. Оно выведет все задания без city_id, невзирая на их статус. Мне казалось там всегда нужно выводить только новые задания, которые только что опубликовали.

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/TasksController.php
> +            $query->andWhere(['and',['city_id' => null],['status' => Task::STATUS_NEW]]);
Опять же, по моему мнению, условие status = new должно присутствовать всегда в запросе.

2020-09-02 04:44 UTC, b1rdex commented on frontend/models/LoginForm.php
> +                $this->addError($attribute, 'Вы ввели неверный пароль');
Текст «Вы ввели неверный email/пароль» из ТЗ, думаю стоит это вернуть.

Вообще, мне кажется не стоит конкретизировать в каком поле ошибка (я про «Пользователя с таким email не существует» выше).

2020-09-02 04:44 UTC, b1rdex commented on frontend/models/Users.php
> +        });
В целом для конкретно этого проекта ок, но это не очень эффективно. Представь ситуацию: у кого-то 1000 избранных и их придётся все загрузить в память, чтобы среди них проверить наличие конкретного id. Для такой ситуации лучше сделать запрос в бд, проверив наличие конкретной записи в таблице избранных.

2020-09-02 04:44 UTC, b1rdex commented on frontend/models/Users.php
> +        return $favourite;
Судя по названию метода, он должен возвращать true/false, а не объект.

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +                    'desc' => ['avg(reviews.rating)' => SORT_DESC],
Не нужно ли сюда добавить вариант asc?

2020-09-02 04:44 UTC, b1rdex commented on frontend/controllers/UsersController.php
> +                    'desc' => ['sum(reviews.task_completion_status ="yes")' => SORT_DESC],
Тот же вопрос про asc

2020-09-02 04:44 UTC, b1rdex commented on frontend/views/landing/index.php
> +                    <h3><a href="#" class="link-regular"><?= $task->name ?></a></h3>
Тут наверно нужно заполнить атрибут href. Хотя хз, т.к. смотреть задания можно только с авторизацией

2020-09-02 04:44 UTC, b1rdex commented on frontend/views/landing/index.php
> +                    <p><?= Html::encode($task->description =
`$task->description =` тут явно лишнее, т.к. нет смысла менять исходный объект. Можно оставить просто `Html::encode(StringHelper::truncate($task->description), 67, '...')`

2020-09-02 04:44 UTC, b1rdex commented on frontend/views/landing/index.php
> +                        <p><a href="#" class="link-regular"><?= $task->category->name ?></a></p>
Тут наверно тоже ссылка

2020-09-02 07:26 UTC, reymezis commented on frontend/controllers/TasksController.php
> +            $query->andWhere(['and',['city_id' => null],['status' => Task::STATUS_NEW]]);
если его не ставить условие выше ->where(['t.status' => Task::STATUS_NEW]) не срабатывает

2020-09-02 07:27 UTC, reymezis commented on frontend/controllers/TasksController.php
> +        ]);
если его не ставить условие выше ->where(['t.status' => Task::STATUS_NEW]) не срабатывает, показывает задания и с другими статусами

2020-09-02 07:27 UTC, reymezis commented on frontend/controllers/UsersController.php
> +                    'desc' => ['avg(reviews.rating)' => SORT_DESC],
по умолчанию сортировка работает в обе стороны

2020-09-02 07:28 UTC, reymezis commented on frontend/controllers/UsersController.php
> +                    'desc' => ['sum(reviews.task_completion_status ="yes")' => SORT_DESC],
тоже самое

2020-09-02 07:29 UTC, reymezis commented on frontend/models/LoginForm.php
> +                $this->addError($attribute, 'Вы ввели неверный пароль');
Здесь я так сделал для удобства пользователя, если сделать только одну эту фразу то Вы ввели неверный email/пароль будет выводится и под полем Пароль что не имеет смысла

2020-09-05 16:57 UTC, reymezis commented on frontend/views/landing/index.php
> +                    <h3><a href="#" class="link-regular"><?= $task->name ?></a></h3>
думаю можно оставить как есть, по заданию ничего не сказано

2020-09-07 02:10 UTC, b1rdex approved these changes

2020-09-07 02:10 UTC, merged