complete db scheme, generate sql scripts
htmlacademy-yii/514921-task-force-1 pull request #8
Opened 2020-02-27 20:31 UTC by reymezis

2020-02-28 02:39 UTC, b1rdex requested changes
Сделал без ООП, а анонимная функция только в array_map, который ты до этого использовал ;) Надеюсь сейчас будет более понятно.

В целом, твой вариант тоже приемлем, но, как по мне, задача программиста – автоматизировать. Поэтому от копипаста всегда следует избавляться, делая небольшие блоки, которые можно переиспользовать.

2020-02-28 02:39 UTC, b1rdex commented on src/converters/CategoriesLoader.php
> +<?php
Попробую на примере этого файла объяснить что я имел в виду.

Первый момент: у тебя сейчас очень сильное дублирование логики и кода, т.к. все файлы делают одно и то же - открывают файл, читают его построчно, формируют массив данных, превращают его в sql inserts.
Т.е. сразу видно, что код можно разделить на 3 компонента, чтобы уменьшить копипаст.

2020-02-28 02:39 UTC, b1rdex commented on src/converters/CategoriesLoader.php
> +$file = new \SplFileObject('data/categories.csv');
Важный момент – следует использовать абсолютные пути к файлам через `__DIR__`, т.к. сейчас твой скрипт будет работать только если его запускать из корня проекта. Т.е. должно быть тут `__DIR__ . '/../../data...'`

2020-02-28 02:39 UTC, b1rdex commented on src/converters/CategoriesLoader.php
> +$file->setFlags(\SplFileObject::READ_CSV |  \SplFileObject::SKIP_EMPTY );
Первый компонент: читалка файла, которая принимает путь к файлу и возвращает все строки из него в виде ассоциативного массива. Да, логика в ней простая, но если вдруг нужно будет добавить какой-то флаг через setFlags, то сейчас это придётся сделать в каждом файле отдельно. Или например поменяются разделители, которые передаются в fgetcsv(), тоже нужно будет сделать это в каждом файле.

Что-то типа такого (для упрощения понимания сделаем на функциях):
```php
function getCsvData(string $path): array {
    $file = new \SplFileObject($path);
    $file->setFlags(SplFileObject::READ_CSV | SplFileObject::READ_AHEAD | SplFileObject::SKIP_EMPTY | SplFileObject::DROP_NEW_LINE);
    
    $headers = $file->fgetcsv();
    
    $result = [];
    // т.к. у нас флаг READ_CSV, то необязательно использовать fgetcsv для чтения файла
    foreach ($file as $row) {
        // соединяем заголовки с данными, в итоге у нас [name => value, name2 => value2]
        $result[] = array_combine($headers, $row);
    }
    
    return $result;
}

// получаем все данные из csv
$rows = getCsvData(__DIR__ . '../data/cities.csv');
```

2020-02-28 02:39 UTC, b1rdex commented on src/converters/CategoriesLoader.php
> +            "$name" => $category,
Второй компонент: трансформирование данных. На этом этапе мы можем заменить имена колонок, какие-то удалить или какие-то добавить; модифицировать данные.

Т.к. мы решили использовать функциональный подход, то тут нам хватит просто array_map:
```php
$transformed = array_map(function (array $row): array {
    return [
        // либо берём просто колонку как она есть в csv
        'name' => $row['name'],
        // либо трансформируем данные под наши нужны
        // тут мы 1) сделали имя колонки как у нас в бд
        // и 2) сделали формат данных как нам нужно (взял у тебя)
        'coordinates' => "ST_PointFromText('POINT({$row['lat']} {$row['long']})')",
		// тут ещё важный момент: типы данных. Из csv всё читается как строки,
		// но в бд нужно вставлять правильный тип. Поэтому int и float нужно кастовать
		// например:
		'city_id' => (int)$row['some-id'],
		'some-float' => (float)$row['some-float'],
    ];
}, $rows);
```

2020-02-28 02:39 UTC, b1rdex commented on src/converters/CategoriesLoader.php
> +}
И третий компонент - формирование sql insert из массива данных, запись в файл.

Что-то типа такого (на самом деле это самая сложная часть):
```php
function writeInsertQueries(string $path, string $tableName, array $rows): void {
    // use взял у тебя, вообще это необязательно должно быть в данных
    // т.к. нас интересовали только insert запросы, а use это уже привязка
    // к конкретной бд, которая может называться по-другому
    $sql = ['USE mydb'];
    
    foreach ($rows as $row) {
        $insertParts = [];
        foreach ($row as $column => $value) {
            switch (gettype($value)) {
                case 'string':
                    // строки нужно взять в кавычки, ты это сделал
                    // но ещё момент – нужно заэскейпить кавычки внутри строк
                    $value = str_replace("'", "\\'", $value);
                    $value = "'{$value}'";
                    break;
                case 'boolean':
                    // делаем трансформеры под всякие типы, которые не пролезут в бд
                    // например, булеан нужно сделать 1 или 0
                    $value = (int)$value;
                    break;
            }
            
            // все значения уже в кавычках, формируем кусочек insert-а
            $insertParts[] = "{$column} = {$value}";
        }
        
        // формируем сам insert, соединяя кусочки через ,
        $sql[] = "insert into {$tableName} set " . implode(', ', $insertParts);
    }
    
    // соединяем все элементы $sql, добавляя ; и перевод строки в конец
    $queries = implode(";\n", $sql);
    file_put_contents($path, $queries);
}
```

2020-03-01 10:54 UTC, reymezis commented on src/converters/CategoriesLoader.php
> +            "$name" => $category,
вот здесь 
'name' => $row['name']
укажем например ключ как в csv файле
'name' => $row['city'] появляется ошибка Undefined index, что странно потому что остальные ключи $row['lat'] и $row['long'] отрабатывают нормально

2020-03-01 10:55 UTC, reymezis commented on src/converters/CategoriesLoader.php
> +            "$name" => $category,
И я не могу понять почему

2020-03-01 11:23 UTC, reymezis commented on src/converters/CategoriesLoader.php
> +            "$name" => $category,
Похоже что есть пробелы перед заголовком city

2020-03-01 11:58 UTC, merged